import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="py-2">
        <nav className="w-full">
          <div className="max-w-7x1 max-auto px-6 md:px-12 xl:px6">
            <div className="flex flex-wrap items-center justify-between">
              <div>Logo</div>
              <div>
                <ul className="flex flex-rowd gap-6">
                  <li>
                    <a href="/about">about</a></li>
                  <li>
                  <a href="/contact">contact</a></li>
                  <li> 
                  <a href="/work">work</a></li>
                </ul>
              </div>
            </div>
          </div>
        </nav>
        </header>
      <main className="pt-5 max-w5x1 max-auto px-6 md:px-12 xl:px6">{children}</main>
      </body>
      
    </html>
  );
}